/**
 * This file was automatically generated by VersionTag.cmake
 */
#pragma once
#define gpiocli_VERSION_MAJOR			0
#define gpiocli_VERSION_MINOR			0
#define gpiocli_VERSION_PATCH			0
#define gpiocli_VERSION_EXTRA			

// Current gpiocli version number as a string.
#define gpiocli_VERSION				"0.0.0"

// Current gpiocli extended version number as a string.
#define gpiocli_VERSION_EXTENDED		"0.0.0"
